### ISSUE TITLE
 Class "App\Utils\CheckDotEnv" not found

### ISSUE THREAD

**Issue by luigimolinaro** [illegalstudio/AITerminal#1]
Installed on MacOS Ventura : 

```
❯ ./ai-terminal execute

In OpenAIServiceV1.php line 35:

  Class "App\Utils\CheckDotEnv" not found



```

```
❯ sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

**Comment by nahime0** [comment]
Can you try to manually create the .env file in the root of the project? 

The content of the .env file shoud be:

```dotenv
# OpenAI
OPENAI_API_KEY=your_api_key
```

**Comment by nahime0** [comment]
Ok, I've found the issue. It happens only in the builded version of the project.
You can still use it running ./ai-terminal from the root of the project.

We'll get back as soon as we solve the issue.

**Comment by nahime0** [comment]
I should have fixed the issue. Can you please test if it's working correctly? 

Thanks
